// src/engines/ontology/vocabulary.js
// Phase 1 ontology vocabulary foundation.
//
// This module intentionally duplicates the currently canonical vocabulary from
// labelMapper, zoneMapper, and styleIdentity without integrating with runtime
// engines yet.

export const CATEGORY_IDS = Object.freeze([
  "jacket",
  "shirt",
  "sweater",
  "hoodie",
  "pants",
  "shorts",
  "shoes",
  "boots",
  "sneakers",
  "accessory",
  "piece",
]);

export const ZONE_IDS = Object.freeze([
  "upper_garment",
  "lower_garment",
  "outerwear",
  "body_garment",
  "footwear",
  "eyewear",
  "bag",
  "hair",
  "lips",
  "fur_trim",
  "logo_text_detail",
  "accessory_jewelry",
  "unknown",
]);

export const MODE_IDS = Object.freeze([
  "balance",
  "contrast",
  "cohesion",
  "natural",
  "explore",
  "emphasis",
]);

export const ROLE_IDS = Object.freeze([
  "minimalist",
  "natural",
  "classic",
  "statement",
  "creative",
  "bold",
  "controlled",
  "modern",
  "refined",
  "balanced",
  "soft",
]);

export const CATEGORY_ALIASES = Object.freeze({
  jacket: Object.freeze(["jackets", "jacket", "outerwear", "coat", "bomber", "overshirt"]),
  shirt: Object.freeze([
    "shirts",
    "shirt",
    "tee",
    "tshirt",
    "t shirt",
    "t-shirt",
    "top",
    "tops",
    "button up",
    "buttonup",
  ]),
  sweater: Object.freeze(["sweaters", "sweater", "knit", "cardigan", "cardigans", "pullover"]),
  hoodie: Object.freeze(["hoodies", "hoodie", "sweatshirt"]),
  pants: Object.freeze([
    "pants",
    "pant",
    "trousers",
    "trouser",
    "jeans",
    "jean",
    "chinos",
    "chino",
    "bottoms",
  ]),
  shorts: Object.freeze(["shorts"]),
  shoes: Object.freeze(["shoes", "shoe", "footwear", "loafers", "loafer"]),
  boots: Object.freeze(["boots", "boot"]),
  sneakers: Object.freeze(["sneakers", "sneaker", "trainers", "trainer"]),
  accessory: Object.freeze([
    "accessories",
    "accessory",
    "bag",
    "bags",
    "hat",
    "hats",
    "belt",
    "belts",
    "watch",
    "strap",
  ]),
});

export const ZONE_ALIASES = Object.freeze({
  upper_garment: Object.freeze([
    "upper",
    "shirt",
    "top",
    "torso",
    "tee",
    "t-shirt",
    "tshirt",
    "blouse",
    "sweater",
    "sweatshirt",
    "hoodie",
    "pullover",
    "tank",
    "camisole",
    "polo",
    "jersey",
    "cardigan",
    "bodice",
  ]),
  lower_garment: Object.freeze([
    "lower",
    "pants",
    "pant",
    "trouser",
    "trousers",
    "jean",
    "jeans",
    "denim",
    "skirt",
    "shorts",
    "legging",
    "leggings",
    "jogger",
    "joggers",
    "chino",
    "chinos",
    "slacks",
  ]),
  outerwear: Object.freeze([
    "outer",
    "outerwear",
    "jacket",
    "coat",
    "blazer",
    "parka",
    "overcoat",
    "trench",
    "windbreaker",
    "anorak",
    "vest",
    "waistcoat",
  ]),
  body_garment: Object.freeze([
    "body garment",
    "body_garment",
    "dress",
    "gown",
    "jumpsuit",
    "romper",
    "onesie",
    "one piece",
    "one-piece",
    "one_piece",
    "suit",
  ]),
  footwear: Object.freeze([
    "shoe",
    "shoes",
    "boot",
    "boots",
    "sneaker",
    "sneakers",
    "trainer",
    "trainers",
    "foot",
    "footwear",
    "loafer",
    "loafers",
    "heel",
    "heels",
    "sandal",
    "sandals",
    "slipper",
    "slippers",
  ]),
  eyewear: Object.freeze(["eyewear", "glass", "glasses", "sunglass", "sunglasses", "spectacles", "frames", "lenses"]),
  bag: Object.freeze(["bag", "bags", "purse", "tote", "tote bag", "handbag", "clutch", "satchel", "backpack", "duffel", "crossbody", "wallet"]),
  hair: Object.freeze(["hair", "hairstyle", "head hair"]),
  lips: Object.freeze(["lip", "lips", "lipstick", "mouth"]),
  fur_trim: Object.freeze(["fur", "trim", "fur trim", "faux fur", "shearling"]),
  logo_text_detail: Object.freeze(["logo", "text", "graphic", "print", "pattern", "lettering", "emblem", "branding", "detail"]),
  accessory_jewelry: Object.freeze([
    "accessor",
    "accessory",
    "accessories",
    "jewel",
    "jewelry",
    "jewellery",
    "necklace",
    "watch",
    "ring",
    "bracelet",
    "earring",
    "earrings",
    "chain",
    "pendant",
    "brooch",
    "pin",
    "belt",
    "scarf",
    "hat",
    "cap",
    "beanie",
  ]),
});
