from pathlib import Path

p=Path('src/server.js')
s=p.read_text()
anchor='''function buildOutfitAnalysis({ dominantHex, topColors, segmentedRegions = [], dinoGarmentRegions = [], pipeline = null, decodedImage = null, perception_v6_mode, v6_mode }) {'''
helper='''function buildPublishedGarmentColorAuthority(garmentZones, fallbackColors = []) {\n  const zones = garmentZones?.zones || {};\n  const orderedKeys = ["upper_garment", "lower_garment", "body_garment", "outerwear", "footwear", "bag", "accessory_jewelry", "eyewear"];\n  const authoritative = [];\n  for (const zone of orderedKeys) {\n    const z = zones[zone];\n    if (!z || z.interpretation === "unknown" || z.one_piece_suppressed) continue;\n    const hex = safeHex(z.hex || z.dominant_color?.hex || "");\n    if (!hex || authoritative.some((c) => c.hex === hex)) continue;\n    authoritative.push({ hex, pct: Math.max(0.01, Math.min(1, Number(z.dominant_color?.pct ?? z.pct ?? 0.25))), name: getColorName(hex), source_zone: zone, source: "published_garment_primary" });\n  }\n  if (!authoritative.length) return fallbackColors;\n  for (const c of fallbackColors) {\n    if (authoritative.length >= 5) break;\n    if (!c?.hex || authoritative.some((x) => x.hex === c.hex)) continue;\n    authoritative.push({ ...c, source: c.source || "global_palette_fallback" });\n  }\n  return authoritative;\n}\n\n'''+anchor
if anchor not in s: raise SystemExit('buildOutfitAnalysis anchor missing')
s=s.replace(anchor,helper,1)
old='''  const garmentAnalysis = inferGarmentAndMaterial({\n    zones: garmentZones?.zones,\n    normalizedColors,\n  });\n\n  const scoreBreakdown = computeScoreBreakdown(colorRoles, normalizedColors);\n  const scoredOutfit = scoreOutfit(scoreBreakdown);\n'''
new='''  const garmentAnalysis = inferGarmentAndMaterial({\n    zones: garmentZones?.zones,\n    normalizedColors,\n  });\n\n  const reasoningColors = buildPublishedGarmentColorAuthority(garmentZones, normalizedColors);\n  const reasoningBaseRoles = assignColorRoles(reasoningColors);\n  const reasoningColorRoles = enforceStructuralPreservation(reasoningBaseRoles, reasoningColors);\n  const scoreBreakdown = computeScoreBreakdown(reasoningColorRoles, reasoningColors);\n  const scoredOutfit = scoreOutfit(scoreBreakdown);\n'''
if old not in s: raise SystemExit('score anchor missing')
s=s.replace(old,new,1)
s=s.replace('  const detectedPalette = buildDetectedPalette(colorRoles, normalizedColors);','  const detectedPalette = buildDetectedPalette(reasoningColorRoles, reasoningColors);',1)
s=s.replace('    color_roles: colorRoles,','''    color_roles: reasoningColorRoles,\n    color_authority: {\n      source: reasoningColors === normalizedColors ? "global_palette_fallback" : "published_garment_primaries",\n      colors: reasoningColors.map((c) => ({ hex: c.hex, name: c.name || getColorName(c.hex), source_zone: c.source_zone || null, source: c.source || null })),\n    },''',1)
s=s.replace('''    why_this_works: buildWhyThisWorks(colorRoles),\n    suggested_adjustment: buildSuggestedAdjustment(scoreBreakdown, colorRoles, best.mode),''','''    why_this_works: buildWhyThisWorks(reasoningColorRoles),\n    suggested_adjustment: buildSuggestedAdjustment(scoreBreakdown, reasoningColorRoles, best.mode),''',1)
p.write_text(s)

test_text='''import test from "node:test";\nimport assert from "node:assert/strict";\nprocess.env.NODE_ENV="test";\nconst { buildOutfitAnalysis } = await import("../src/server.js");\n\nfunction img(){\n  const data=new Uint8Array(100*140*4);\n  for(let y=0;y<140;y++) for(let x=0;x<100;x++){\n    let c=[190,160,130];\n    if(y>20&&y<65)c=[96,50,30];\n    if(y>=65&&y<125)c=[78,96,79];\n    const i=(y*100+x)*4; data.set([...c,255],i);\n  }\n  return {width:100,height:140,data};\n}\nconst regions=[\n {id:"upper",source_type:"grounding_dino",zone:"upper_garment",label:"shirt",segment_label:"shirt",confidence:.95,coverage:.25,bounding_box:{x:.25,y:.15,width:.5,height:.3},dominant_hex:"#60321E",region_colors:[{hex:"#60321E",pct:.96}]},\n {id:"lower",source_type:"grounding_dino",zone:"lower_garment",label:"pants",segment_label:"pants",confidence:.95,coverage:.4,bounding_box:{x:.25,y:.48,width:.5,height:.42},dominant_hex:"#4E604F",region_colors:[{hex:"#4E604F",pct:.8}]},\n];\n\ntest("published garment primaries become downstream color authority",()=>{\n const r=buildOutfitAnalysis({dominantHex:"#0D131E",topColors:[{hex:"#0D131E",pct:.67},{hex:"#4E604F",pct:.25},{hex:"#60321E",pct:.08}],segmentedRegions:regions,decodedImage:img(),perception_v6_mode:"assist"});\n assert.equal(r.color_authority.source,"published_garment_primaries");\n const authority=r.color_authority.colors.map(c=>c.hex.toUpperCase());\n assert.ok(authority.includes("#60321E"));\n assert.ok(authority.includes("#4E604F"));\n assert.match(r.why_this_works,/Rich Brown|Muted Forest Green/i);\n});\n'''
Path('test/colorAuthorityV1.test.js').write_text(test_text)
