from pathlib import Path
p=Path('src/server.js')
s=p.read_text()
old='import { analyzePerceptionV6 } from "./intelligence/perceptionV6/index.js";'
new=old+'\nimport { attachColorEvidenceToZones } from "./intelligence/colorEvidence/index.js";'
if old not in s: raise SystemExit('import anchor missing')
s=s.replace(old,new,1)
old_sig='export function resolveConsumerZonePrimary(type, zoneData, clusters = []) {'
new_sig='export function resolveConsumerZonePrimary(type, zoneData, clusters = [], colorEvidence = null) {'
if old_sig not in s: raise SystemExit('resolver signature missing')
s=s.replace(old_sig,new_sig,1)
anchor='''  const corroborated = signatureCorroborates || supportCorroborates || locallyConsistent;\n  const finalizedTrusted = !!finalizedHex && confidence >= minimumConfidence && consistencyValid && publicationAccepted && corroborated;\n\n  if (finalizedTrusted) {'''
replacement='''  const corroborated = signatureCorroborates || supportCorroborates || locallyConsistent;\n  const finalizedTrusted = !!finalizedHex && confidence >= minimumConfidence && consistencyValid && publicationAccepted && corroborated;\n  const evidenceHex = safeHex(colorEvidence?.consensus_hex || "");\n  const evidenceSupported = colorEvidence?.decision_state === "supported" && Number(colorEvidence?.region_purity || 0) >= 0.80 && Number(colorEvidence?.family_consensus || 0) >= 0.80;\n  const evidenceVsRawDistance = evidenceHex && rawHex ? colorDistanceLab(evidenceHex, rawHex) : null;\n  const evidenceVsFinalizedDistance = evidenceHex && finalizedHex ? colorDistanceLab(evidenceHex, finalizedHex) : null;\n  const rawTraits = rawHex ? getPerceptualTraits(rawHex) : null;\n  const rawLooksDarkNeutral = !!rawHex && (getLight(rawHex) <= 0.22 || Number(rawTraits?.chroma_magnitude || 0) < 18);\n  const evidenceCanCorrectDarkContamination = evidenceSupported && !!evidenceHex && rawLooksDarkNeutral && evidenceVsRawDistance !== null && evidenceVsRawDistance >= 18 && (!finalizedHex || evidenceVsFinalizedDistance < 18);\n\n  if (evidenceCanCorrectDarkContamination) {\n    return {\n      status: "resolved",\n      hex: evidenceHex,\n      source: "color_evidence_v2_consensus",\n      confidence,\n      finalized_vs_raw_lab: finalizedVsRawDistance,\n      evidence: {\n        region_purity: Number(colorEvidence.region_purity || 0),\n        family_consensus: Number(colorEvidence.family_consensus || 0),\n        consensus_family: colorEvidence.consensus_family || null,\n        consensus_hex: evidenceHex,\n        evidence_vs_raw_lab: evidenceVsRawDistance,\n        evidence_vs_finalized_lab: evidenceVsFinalizedDistance,\n      },\n      corroboration: { signature: signatureCorroborates, support: supportCorroborates, raw_agreement: locallyConsistent },\n    };\n  }\n\n  if (finalizedTrusted) {'''
if anchor not in s: raise SystemExit('resolver anchor missing')
s=s.replace(anchor,replacement,1)
s=s.replace('function inferGarmentAndMaterial({ zones, normalizedColors = [] }) {','function inferGarmentAndMaterial({ zones, normalizedColors = [], colorEvidenceByZone = {} }) {',1)
s=s.replace('const consumerColorResolution = resolveConsumerZonePrimary(type, zoneData, clusters);','const consumerColorResolution = resolveConsumerZonePrimary(type, zoneData, clusters, colorEvidenceByZone?.[type] || null);',1)
old_call='''  const garmentAnalysis = inferGarmentAndMaterial({\n    zones: garmentZones?.zones,\n    normalizedColors,\n  });'''
new_call='''  const colorEvidenceShadowZones = attachColorEvidenceToZones({\n    zones: garmentZones?.zones || {},\n    regions: garmentEvidenceRegions,\n    decodedImage,\n  });\n  const colorEvidenceByZone = Object.fromEntries(\n    Object.entries(colorEvidenceShadowZones || {}).map(([zone, value]) => [zone, value?.color_evidence_v1 || null])\n  );\n  const garmentAnalysis = inferGarmentAndMaterial({\n    zones: garmentZones?.zones,\n    normalizedColors,\n    colorEvidenceByZone,\n  });'''
if old_call not in s: raise SystemExit('garment analysis call missing')
s=s.replace(old_call,new_call,1)
p.write_text(s)

Path('test/colorEvidenceV2.test.js').write_text('''import test from "node:test";\nimport assert from "node:assert/strict";\nprocess.env.NODE_ENV="test";\nconst { resolveConsumerZonePrimary } = await import("../src/server.js");\n\nfunction zone(hex, confidence=75){ return { hex, dominant_color:{hex}, confidence, decision_consistency:{valid:true}, publication_decision:"publish", signature_color:{hex} }; }\n\ntest("strong green consensus corrects dark-neutral raw contamination",()=>{\n const r=resolveConsumerZonePrimary("lower_garment", zone("#4E604F",75), [{base:"#0D131E",pct:.67},{base:"#4E604F",pct:.25}], {decision_state:"supported",region_purity:.91,family_consensus:1,consensus_family:"green",consensus_hex:"#4E604F"});\n assert.equal(r.hex.toUpperCase(),"#4E604F");\n assert.equal(r.source,"color_evidence_v2_consensus");\n});\n\ntest("weak evidence cannot override raw cluster",()=>{\n const r=resolveConsumerZonePrimary("lower_garment", { ...zone("#4E604F",55), signature_color:null, support_colors:[] }, [{base:"#0D131E",pct:.67},{base:"#4E604F",pct:.25}], {decision_state:"observed",region_purity:.62,family_consensus:.6,consensus_family:"green",consensus_hex:"#4E604F"});\n assert.equal(r.hex.toUpperCase(),"#0D131E");\n assert.notEqual(r.source,"color_evidence_v2_consensus");\n});\n\ntest("strong evidence does not override a chromatic raw primary unless it agrees with finalized identity",()=>{\n const r=resolveConsumerZonePrimary("upper_garment", zone("#60321E",90), [{base:"#60321E",pct:.8}], {decision_state:"supported",region_purity:.94,family_consensus:1,consensus_family:"green",consensus_hex:"#4E604F"});\n assert.equal(r.hex.toUpperCase(),"#60321E");\n assert.notEqual(r.source,"color_evidence_v2_consensus");\n});\n''')
