from pathlib import Path

p=Path('src/server.js')
s=p.read_text()
anchor='''  function buildItem(type, zoneData) {\n    if (!zoneData?.hex) return null;'''
replacement='''  function resolveConsumerZonePrimary(type, zoneData, clusters = []) {\n    const finalizedHex = safeHex(zoneData?.dominant_color?.hex || zoneData?.hex || "");\n    const rawHex = safeHex(clusters?.[0]?.base || "");\n    const signatureHex = safeHex(zoneData?.signature_color?.hex || "");\n    const confidence = Number(zoneData?.confidence || zoneData?.score || 0);\n    const minimumConfidence = type === "lower_garment" ? 60 : type === "upper_garment" ? 45 : 56;\n    const consistency = zoneData?.decision_consistency;\n    const consistencyValid = consistency ? consistency.valid !== false : true;\n    const publicationAccepted = zoneData?.publication_decision !== "reject" && zoneData?.validation_decision !== "rejected";\n    const finalizedVsRawDistance = finalizedHex && rawHex ? colorDistanceLab(finalizedHex, rawHex) : null;\n    const signatureCorroborates = finalizedHex && signatureHex ? colorDistanceLab(finalizedHex, signatureHex) < 18 : false;\n    const supportCorroborates = finalizedHex && Array.isArray(zoneData?.support_colors)\n      ? zoneData.support_colors.some((c) => safeHex(c?.hex) && colorDistanceLab(finalizedHex, c.hex) < 18)\n      : false;\n    const locallyConsistent = finalizedVsRawDistance === null || finalizedVsRawDistance < 18;\n    const corroborated = signatureCorroborates || supportCorroborates || locallyConsistent;\n    const finalizedTrusted = !!finalizedHex && confidence >= minimumConfidence && consistencyValid && publicationAccepted && corroborated;\n\n    if (finalizedTrusted) {\n      return {\n        status: "resolved",\n        hex: finalizedHex,\n        source: "finalized_zone_primary",\n        confidence,\n        finalized_vs_raw_lab: finalizedVsRawDistance,\n        corroboration: { signature: signatureCorroborates, support: supportCorroborates, raw_agreement: locallyConsistent },\n      };\n    }\n\n    if (rawHex) {\n      return {\n        status: finalizedHex && finalizedVsRawDistance >= 18 ? "uncertain" : "fallback",\n        hex: rawHex,\n        source: "local_cluster_fallback",\n        confidence,\n        finalized_vs_raw_lab: finalizedVsRawDistance,\n        corroboration: { signature: signatureCorroborates, support: supportCorroborates, raw_agreement: locallyConsistent },\n      };\n    }\n\n    return { status: "uncertain", hex: finalizedHex || null, source: finalizedHex ? "low_confidence_finalized" : "no_color_evidence", confidence, finalized_vs_raw_lab: finalizedVsRawDistance, corroboration: { signature: signatureCorroborates, support: supportCorroborates, raw_agreement: locallyConsistent } };\n  }\n\n  function buildItem(type, zoneData) {\n    if (!zoneData?.hex) return null;'''
if anchor not in s: raise SystemExit('buildItem anchor missing')
s=s.replace(anchor,replacement,1)
old='''    const dominant = clusters[0] || { base: zoneData.hex, pct: 1 };\n\n    const dominantTraits = getPerceptualTraits(dominant.base);'''
new='''    const rawDominant = clusters[0] || { base: zoneData.hex, pct: 1 };\n    const consumerColorResolution = resolveConsumerZonePrimary(type, zoneData, clusters);\n    const dominant = { ...rawDominant, base: consumerColorResolution.hex || rawDominant.base };\n\n    const dominantTraits = getPerceptualTraits(dominant.base);'''
if old not in s: raise SystemExit('dominant anchor missing')
s=s.replace(old,new,1)
old2='''      headwear_debug_values: buildHeadwearDebugValues(zoneData),\n      dominant_color: dominantColor,\n      primary_color: compactColorRead(dominantColor),'''
new2='''      headwear_debug_values: buildHeadwearDebugValues(zoneData),\n      consumer_color_resolution: consumerColorResolution,\n      dominant_color: dominantColor,\n      primary_color: compactColorRead(dominantColor),'''
if old2 not in s: raise SystemExit('return anchor missing')
s=s.replace(old2,new2,1)
p.write_text(s)

Path('test/publicationConsistencyAccuracyV1.test.js').write_text('''import test from "node:test";\nimport assert from "node:assert/strict";\nprocess.env.NODE_ENV = "test";\nconst { buildOutfitAnalysis } = await import("../src/server.js");\n\nfunction decodedImage(){\n  const data = new Uint8Array(100*140*4);\n  for(let y=0;y<140;y++) for(let x=0;x<100;x++){\n    let c=[180,150,120];\n    if(y>20&&y<64)c=[96,50,30];\n    if(y>=64&&y<125)c=[78,96,79];\n    const i=(y*100+x)*4; data.set([...c,255],i);\n  }\n  return {width:100,height:140,data};\n}\n\nconst regions=[\n  {id:"upper",source_type:"grounding_dino",zone:"upper_garment",label:"shirt",segment_label:"shirt",confidence:.95,coverage:.25,bounding_box:{x:.22,y:.15,width:.56,height:.3},dominant_hex:"#60321E",region_colors:[{hex:"#60321E",pct:.96},{hex:"#20110B",pct:.04}]},\n  {id:"lower",source_type:"grounding_dino",zone:"lower_garment",label:"pants",segment_label:"pants",confidence:.95,coverage:.41,bounding_box:{x:.25,y:.47,width:.5,height:.42},dominant_hex:"#4E604F",region_colors:[{hex:"#0D131E",pct:.67},{hex:"#1E2E23",pct:.25},{hex:"#4E604F",pct:.08}]},\n];\n\ntest("consumer garment primary honors corroborated finalized zone instead of reclustering it away",()=>{\n  const r=buildOutfitAnalysis({dominantHex:"#0D131E",topColors:[{hex:"#0D131E",pct:.67},{hex:"#4E604F",pct:.25},{hex:"#60321E",pct:.08}],segmentedRegions:regions,decodedImage:decodedImage(),perception_v6_mode:"assist"});\n  const lowerZone=r.garment_zones.zones.lower_garment;\n  const lowerItem=r.garment_analysis.detected_items.find(x=>x.type==="lower_garment");\n  assert.ok(lowerZone); assert.ok(lowerItem);\n  assert.equal(lowerItem.primary_color.hex.toUpperCase(), lowerZone.dominant_color.hex.toUpperCase());\n  assert.equal(lowerItem.consumer_color_resolution.status,"resolved");\n  assert.equal(lowerItem.consumer_color_resolution.source,"finalized_zone_primary");\n});\n''')
