from pathlib import Path

p=Path('src/server.js')
s=p.read_text()
anchor='''function inferGarmentAndMaterial({ zones, normalizedColors = [] }) {'''
helper='''export function resolveConsumerZonePrimary(type, zoneData, clusters = []) {\n  const finalizedHex = safeHex(zoneData?.dominant_color?.hex || zoneData?.hex || "");\n  const rawHex = safeHex(clusters?.[0]?.base || "");\n  const signatureHex = safeHex(zoneData?.signature_color?.hex || "");\n  const confidence = Number(zoneData?.confidence || zoneData?.score || 0);\n  const minimumConfidence = type === "lower_garment" ? 60 : type === "upper_garment" ? 45 : 56;\n  const consistency = zoneData?.decision_consistency;\n  const consistencyValid = consistency ? consistency.valid !== false : true;\n  const publicationAccepted = zoneData?.publication_decision !== "reject" && zoneData?.validation_decision !== "rejected";\n  const finalizedVsRawDistance = finalizedHex && rawHex ? colorDistanceLab(finalizedHex, rawHex) : null;\n  const signatureCorroborates = finalizedHex && signatureHex ? colorDistanceLab(finalizedHex, signatureHex) < 18 : false;\n  const supportCorroborates = finalizedHex && Array.isArray(zoneData?.support_colors)\n    ? zoneData.support_colors.some((c) => safeHex(c?.hex) && colorDistanceLab(finalizedHex, c.hex) < 18)\n    : false;\n  const locallyConsistent = finalizedVsRawDistance === null || finalizedVsRawDistance < 18;\n  const corroborated = signatureCorroborates || supportCorroborates || locallyConsistent;\n  const finalizedTrusted = !!finalizedHex && confidence >= minimumConfidence && consistencyValid && publicationAccepted && corroborated;\n\n  if (finalizedTrusted) {\n    return {\n      status: "resolved",\n      hex: finalizedHex,\n      source: "finalized_zone_primary",\n      confidence,\n      finalized_vs_raw_lab: finalizedVsRawDistance,\n      corroboration: { signature: signatureCorroborates, support: supportCorroborates, raw_agreement: locallyConsistent },\n    };\n  }\n\n  if (rawHex) {\n    return {\n      status: finalizedHex && finalizedVsRawDistance >= 18 ? "uncertain" : "fallback",\n      hex: rawHex,\n      source: "local_cluster_fallback",\n      confidence,\n      finalized_vs_raw_lab: finalizedVsRawDistance,\n      corroboration: { signature: signatureCorroborates, support: supportCorroborates, raw_agreement: locallyConsistent },\n    };\n  }\n\n  return {\n    status: "uncertain",\n    hex: finalizedHex || null,\n    source: finalizedHex ? "low_confidence_finalized" : "no_color_evidence",\n    confidence,\n    finalized_vs_raw_lab: finalizedVsRawDistance,\n    corroboration: { signature: signatureCorroborates, support: supportCorroborates, raw_agreement: locallyConsistent },\n  };\n}\n\n'''+anchor
if anchor not in s: raise SystemExit('inferGarmentAndMaterial anchor missing')
s=s.replace(anchor,helper,1)
old='''    const dominant = clusters[0] || { base: zoneData.hex, pct: 1 };\n\n    const dominantTraits = getPerceptualTraits(dominant.base);'''
new='''    const rawDominant = clusters[0] || { base: zoneData.hex, pct: 1 };\n    const consumerColorResolution = resolveConsumerZonePrimary(type, zoneData, clusters);\n    const dominant = { ...rawDominant, base: consumerColorResolution.hex || rawDominant.base };\n\n    const dominantTraits = getPerceptualTraits(dominant.base);'''
if old not in s: raise SystemExit('dominant anchor missing')
s=s.replace(old,new,1)
old2='''      headwear_debug_values: buildHeadwearDebugValues(zoneData),\n      dominant_color: dominantColor,\n      primary_color: compactColorRead(dominantColor),'''
new2='''      headwear_debug_values: buildHeadwearDebugValues(zoneData),\n      consumer_color_resolution: consumerColorResolution,\n      dominant_color: dominantColor,\n      primary_color: compactColorRead(dominantColor),'''
if old2 not in s: raise SystemExit('return anchor missing')
s=s.replace(old2,new2,1)
old3='''      ...buildGarmentColorProfile({\n        zoneKey: type,\n        mode: itemMode,\n        dominantColor,\n        supportColors,\n        accentColors,\n      }),\n    };'''
new3='''      ...buildGarmentColorProfile({\n        zoneKey: type,\n        mode: itemMode,\n        dominantColor,\n        supportColors,\n        accentColors,\n      }),\n      // Accuracy decision owns the consumer-facing primary after profile metadata is merged.\n      dominant_color: dominantColor,\n      primary_color: compactColorRead(dominantColor),\n      color_identity_summary: buildColorIdentitySummary(dominantColor?.color_identity),\n    };'''
if old3 not in s: raise SystemExit('profile serialization anchor missing')
s=s.replace(old3,new3,1)
p.write_text(s)

Path('test/publicationConsistencyAccuracyV1.test.js').write_text('''import test from "node:test";\nimport assert from "node:assert/strict";\nconst { resolveConsumerZonePrimary } = await import("../src/server.js");\n\ntest("trusted finalized primary wins only with confidence, consistency and corroboration",()=>{\n  const r=resolveConsumerZonePrimary("lower_garment", {\n    hex:"#4E604F", dominant_color:{hex:"#4E604F"}, signature_color:{hex:"#4E604F"}, confidence:75, decision_consistency:{valid:true}\n  }, [{base:"#0D131E",pct:.67},{base:"#1E2E23",pct:.25},{base:"#4E604F",pct:.08}]);\n  assert.equal(r.status,"resolved");\n  assert.equal(r.source,"finalized_zone_primary");\n  assert.equal(r.hex.toUpperCase(),"#4E604F");\n  assert.equal(r.corroboration.signature,true);\n});\n\ntest("low-confidence finalized color does not get forced over local evidence",()=>{\n  const r=resolveConsumerZonePrimary("lower_garment", {\n    hex:"#4E604F", dominant_color:{hex:"#4E604F"}, signature_color:{hex:"#4E604F"}, confidence:37, decision_consistency:{valid:true}\n  }, [{base:"#0D131E",pct:.67},{base:"#4E604F",pct:.08}]);\n  assert.notEqual(r.status,"resolved");\n  assert.equal(r.source,"local_cluster_fallback");\n  assert.equal(r.hex.toUpperCase(),"#0D131E");\n});\n\ntest("invalid decision consistency prevents finalized primary from being forced",()=>{\n  const r=resolveConsumerZonePrimary("upper_garment", {\n    hex:"#60321E", dominant_color:{hex:"#60321E"}, signature_color:{hex:"#60321E"}, confidence:90, decision_consistency:{valid:false,issues:["conflict"]}\n  }, [{base:"#20110B",pct:.56},{base:"#60321E",pct:.44}]);\n  assert.notEqual(r.status,"resolved");\n  assert.equal(r.source,"local_cluster_fallback");\n});\n''')
