from pathlib import Path

path = Path('src/intelligence/accessoryPublicationBridgeV1.js')
source = path.read_text()
old = 'function bridgeInstance(instance, region) {\n  if (!region) return instance;\n'
new = '''function bridgeInstance(instance, region) {\n  if (!region) {\n    const type = instanceType(instance);\n    const jewelry = new Set(["watch", "earrings", "ring", "bracelet", "necklace", "chain", "pendant", "shoe_hardware"]);\n    if (!jewelry.has(type)) return instance;\n\n    const decision = String(instance?.color_publication_decision || "");\n    const existingWithhold = /withhold|identity_only/.test(decision) || instance?.validation_decision === "identity_only";\n    const primaryHex = safeHex(instance?.hex || instance?.dominant_hex || instance?.primary_color?.hex || instance?.dominant_color?.hex);\n    const rows = [\n      ...(Array.isArray(instance?.object_local_colors) ? instance.object_local_colors : []),\n      ...(Array.isArray(instance?.region_colors) ? instance.region_colors : []),\n      ...(Array.isArray(instance?.detected_colors) ? instance.detected_colors : []),\n    ];\n    const uniqueHexes = [...new Set(rows.map((row) => safeHex(row?.hex)).filter(Boolean))];\n    let suspiciousWarmPrimary = false;\n    if (primaryHex) {\n      const [r, g, b] = [1, 3, 5].map((i) => Number.parseInt(primaryHex.slice(i, i + 2), 16));\n      const max = Math.max(r, g, b), min = Math.min(r, g, b);\n      suspiciousWarmPrimary = r > g && g > b && (max - min) >= 18 && r >= 120 && g >= 90 && b >= 55;\n    }\n    const suspiciousNoisyPalette = uniqueHexes.length >= 4;\n    if (!existingWithhold && !suspiciousWarmPrimary && !suspiciousNoisyPalette) return instance;\n\n    return {\n      ...instance,\n      object_local_colors: [],\n      support_colors: [],\n      secondary_colors: [],\n      region_colors: [],\n      detected_colors: [],\n      hex: null,\n      dominant_hex: null,\n      dominant_color: null,\n      primary_color: null,\n      signature_color: null,\n      color_publication_decision: existingWithhold ? decision || "withhold_unvalidated_color" : "withhold_unvalidated_color",\n      validation_decision: "identity_only",\n      validation_reason: existingWithhold ? (instance?.validation_reason || "accessory_color_already_withheld") : "suspicious_accessory_palette_without_ownership_region",\n      color_authority_source: "piece_color_ownership_v1",\n      stale_accessory_palette_suppressed: true,\n      accessory_final_publication_gate_v1: true,\n    };\n  }\n'''
if new not in source:
    if old not in source:
        raise SystemExit('bridgeInstance no-region anchor not found')
    source = source.replace(old, new, 1)
path.write_text(source)
print('wired scoped no-region accessory publication gate')
